"""add query_logs table

Revision ID: 23249eb8ffb0
Revises: e3b45dfaee44
Create Date: 2026-09-03 18:44:12.713851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23249eb8ffb0'
down_revision: Union[str, Sequence[str], None] = 'e3b45dfaee44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('chunk_ids', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_logs')
    # ### end Alembic commands ###
