"""add file_size to documents

Revision ID: c1657862d77a
Revises: e3b45dfaee44
Create Date: 2026-07-13 16:58:17.081244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1657862d77a'
down_revision: Union[str, Sequence[str], None] = 'e3b45dfaee44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
